import java.util.Arrays;

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
   10: 1,2,5,10
   15: 1,3,5,15
   21: 1,3,7,21
   28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

public class Test {

    public static void main(String[] args) {
        System.out.println(factorCount(500));
    }

    // n & n+1 must have no common divisor
    public static int factorCount(int limit) {
        int cnt = 0;
        for (int i=0; cnt<=limit; i++) {
            if (i % 2 == 0) {
                cnt = count(i/2) * count(i+1);
            } else {
                cnt = count(i) * count((i+1)/2);
            }
            if (cnt >= 500)
                return i
        }
        return -1;
    }

    public static int count(int n) {
        int result = 1;
        int divisor = 2;
        for (; divisor*divisor<n; divisor++) {
            if (n % divisor == 0)
                result += 2;
        if (divisor*divisor == n)
            result++;
        return result;
        }
    }
}
